In [1]:
import torch

In [2]:
class one_layer_net(torch.nn.Module):    
    # Constructor
    def __init__(self, input_size, weight=None, bias=None):
        super(one_layer_net, self).__init__() 
        self.batch_norm_1 = torch.nn.BatchNorm2d(input_size)
        if weight != None:
          self.batch_norm_1.weight = torch.nn.parameter.Parameter(weight)
        if bias != None:
          self.batch_norm_1.bias = torch.nn.parameter.Parameter(bias)
    def forward(self, x):
        y_pred = self.batch_norm_1(x)
        return y_pred

In [3]:
batch_size = 1
feature_num = 1
height = 1
width = 5

new_weight = torch.rand(batch_size, feature_num)
new_bias = torch.rand(batch_size, feature_num)

model = one_layer_net(feature_num, weight = new_weight, bias = new_bias)
# model = one_layer_net(feature_num)
print('Network Structure : torch.nn.Linear(2,1) :\n',model.batch_norm_1)
print('Weight Of Network :\n',model.batch_norm_1.weight)
print('Bias Of Network :\n',model.batch_norm_1.bias)

Network Structure : torch.nn.Linear(2,1) :
 BatchNorm2d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
Weight Of Network :
 Parameter containing:
tensor([[0.2540]], requires_grad=True)
Bias Of Network :
 Parameter containing:
tensor([[0.8422]], requires_grad=True)


In [7]:

input = torch.randn(batch_size, feature_num, height, width)
print(input)
out = model(input)
print("Model Output")
print(out)

firstDimenMean=torch.Tensor.mean(input[0][0])
firstDimenVar=torch.Tensor.var(input[0][0], False)
print(model.batch_norm_1.eps)
print(firstDimenMean)
print(firstDimenVar)
print(torch.pow(firstDimenVar+model.batch_norm_1.eps, 0.5))

tensor([[[[-0.6692, -0.9939, -2.0425,  0.3442, -1.1473]]]])
Model Output
tensor([[[[0.9187, 0.8119, 0.4666, 1.2523, 0.7614]]]],
       grad_fn=<NativeBatchNormBackward0>)
1e-05
tensor(-0.9017)
tensor(0.5953)
tensor(0.7716)


In [6]:
batchnormone=((input[0][0][0][0]-firstDimenMean) /(torch.pow(firstDimenVar+model.batch_norm_1.eps, 0.5) )) * model.batch_norm_1.weight[0] + model.batch_norm_1.bias[0]
print(batchnormone)

tensor([0.8956], grad_fn=<AddBackward0>)


In [ ]:
weight_to_write = model.batch_norm_1.weight.tolist()[0][0]
bias_to_write = model.batch_norm_1.bias.tolist()[0][0]
input_to_write = input.tolist()[0][0]
golden_to_write = out.tolist()[0][0]

In [ ]:
save_path = "drive/MyDrive/@台灣大學電機系_四下/五_積體電路設計實驗/Final_Project/code/Batch_Norm"
weight_file = save_path + "/weight.csv"
bias_file = save_path + "/bias.csv"
input_file = save_path + "/input.csv"
golden_file = save_path + "/golden.csv"

import csv
with open(weight_file, 'w', newline='') as file:
  writer = csv.writer(file)
  writer.writerow(weight_to_write)
with open(bias_file, 'w', newline='') as file:
  writer = csv.writer(file)
  writer.writerow(bias_to_write)
with open(input_file, 'w', newline='') as file:
  writer = csv.writer(file)
  writer.writerow(input_to_write)
with open(golden_file, 'w', newline='') as file:
  writer = csv.writer(file)
  writer.writerow(golden_to_write)

Error: ignored